---
id: fukuoka03-rubima-reboot
base_name: rubyist-magazine-reboot
tags:
- ruby
presentation_date: '2023-02-18'
presentation_start_time:
presentation_end_time:
version: 2023.2.18.0
licenses: []
slideshare_id: fukuoka03rubimarebootrubyistmagazinerebootpdf
speaker_deck_id: rubyist-magazine-reboot
vimeo_id:
youtube_id:
width: 1920
height: 1080
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
